"""add_access_token_and_timestamps_to_shops

Revision ID: 278cc84879a0
Revises: 79f2a6706b7f
Create Date: 2025-05-17 10:52:26.568485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278cc84879a0'
down_revision: Union[str, None] = '79f2a6706b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('access_token', sa.String(), nullable=False))
    op.add_column('shops', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('shops', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'updated_at')
    op.drop_column('shops', 'created_at')
    op.drop_column('shops', 'access_token')
    # ### end Alembic commands ###
